- Makefile
- orion/analysis.py
- orion/explorer.py
- orion/model.py
- setup.py
- tox.ini
Hi,
I implemented the changes to the db schema mentioned [here](https://github.com/D3-AI/Orion/pull/57) & [here](https://github.com/D3-AI/Orion/issues/48).
I also modified the Orion Explorer to work with the new structure. 
The proposed interaction with the Orion Explorer would be:
```
explorer = OrionExplorer(database='orion')
explorer.add_pipeline('lstm_dynamic_threshold', '../orion/pipelines/lstm_dynamic_threshold.json')
explorer.add_dataset('testdataset')
explorer.add_signal('E-1', 'testdataset')
explorer.add_signal('S-1', 'testdataset')
explorer.run_experiment(name='testexperiment', project='testproject', pipeline='lstm_dynamic_threshold', dataset='testdataset')
```
`run_experiment()` will execute a Datarun for each Signal in the Dataset. 
@csala @dyuliu Can you please have a look if …
> Update db schema

- orion/explorer.py
resolve #61 
Improve OrionExplorer to optionally store intermediate pipeline outputs, which are specified in the pipeline JSON file, to mongoDB GridFs.
> Intermediate outputs of pipeline

- orion/pipelines/arima.json
- orion/pipelines/cyclegan.json
- orion/pipelines/lstm_cyclegan.json
- setup.py
Add two anomaly detection pipelines:
- Arima 
- LSTM-CycleGAN
> add arima and lstm-cyclegan pipelines

- Makefile
- orion/analysis.py
- setup.py
- tests/test_analysis.py
- tox.ini
> Issue 49 no events crash

- orion/cli.py
- orion/evaluation.py
- tests/test_evaluation.py
Resolve #70 
Add way to decide whether to holdout test data on fit or not.
> Make holdout optional

- setup.py
> fix file encoding and decoding issues during installation

- .gitignore
- orion/db/schema.py
> fix bugs when saving signalrun if no event got detected

- orion/evaluation/README.md
> Updated Evaluation README

- orion/pipelines/tadgan.json
- orion/primitives/jsons/orion.primitives.tadgan.score_anomalies.json
- orion/primitives/tadgan.py
> Added critic and reconstruction error combination option

- orion/core.py
- tests/test_core.py
> Change parameter name

- orion/benchmark.py
- orion/evaluation/common.py
- tests/test_benchmark.py
> Benchmark exception handling

- orion/benchmark.py
- tests/test_benchmark.py
> Move loading ground truth with loading the signal

- orion/primitives/azure_anomaly_detector.py
- orion/primitives/jsons/orion.primitives.azure_anomaly_detector.detect_anomalies.json
- setup.py
Resolve #123.
In addition, we remove the exception handling since it is taken care of in the benchmark.
> Timestamp timezone and exceptions

- orion/benchmark.py
- tests/test_benchmark.py
> Update `holdout` to be `test_split`

- orion/primitives/jsons/orion.primitives.tadgan.score_anomalies.json
- orion/primitives/tadgan.py
Resolve #132. Adjust smooth window setting.
> Update assignment of critic/error smooth window

- orion/primitives/timeseries_anomalies.py
> Handling series as array in `timeseries_anomalies`

- README.md
Update the description of the different parts of the tutorials. Checked in the preview it looks good.
> Updates to the ReadMe

- BENCHMARK.md
- benchmark/leaderboard.md
- docs/user_guides/benchmarking.rst
Resolve #148.
New file `benchmark/leaderboard.md` to hold the latest results.
> Fix benchmark docs

- Makefile
- orion/evaluation/README.md
- setup.py
> Update evaluation README

- docs/api_reference/index.rst
- docs/api_reference/prim.rst
- docs/user_guides/evaluation_doc.rst
- docs/user_guides/primitives_pipelines/pipelines.rst
- docs/user_guides/primitives_pipelines/primitives.rst
- docs/user_guides/primitives_pipelines/primitives/LSTMTimeSeriesRegressor.rst
- docs/user_guides/primitives_pipelines/primitives/MinMaxScaler.rst
- docs/user_guides/primitives_pipelines/primitives/SimpleImputer.rst
- docs/user_guides/primitives_pipelines/primitives/TadGAN.rst
- docs/user_guides/primitives_pipelines/primitives/arima.rst
- docs/user_guides/primitives_pipelines/primitives/find_anomalies.rst
- docs/user_guides/primitives_pipelines/primitives/intervals_to_mask.rst
- docs/user_guides/primitives_pipelines/primitives/regression_errors.rst
- docs/user_guides/primitives_pipelines/primitives/rolling_window_sequences.rst
- docs/user_guides/primitives_pipelines/primitives/score_anomalies.rst
- docs/user_guides/primitives_pipelines/primitives/time_segments_aggregate.rst
- orion/primitives/jsons/orion.primitives.tadgan.TadGAN.json
- orion/primitives/tadgan.py
- setup.py
> Primitives documentation and fix tadgan iteration critic variable name

- README.md
Add TadGAN paper link on the top
> Update README.md - Add TadGAN paper link

- docs/index.rst
> Fix bullet point issue

- orion/primitives/tadgan.py
> Save TadGAN object

- orion/data.py
As I describe on the following issue, there is an interger overfow issue on Windows systems.
Resolve #212.
> Integer overflow correction

- orion/primitives/tadgan.py
Update properties of temp file used to save TadGAN networks.
> Update TadGAN save model

- setup.py
> Fix colab conflict 

- BENCHMARK.md
- orion/benchmark.py
- orion/progress.py
- orion/results.py
- setup.py
- tests/test_benchmark.py
> Refactor `benchmark`

- docs/user_guides/primitives_pipelines/primitives/rolling_window_sequences.rst
- notebooks/pipelines/lstm_dynamic_threshold.ipynb
- orion/pipelines/verified/lstm_dynamic_threshold/lstm_dynamic_threshold.json
> Intermediate output notebook

- orion/db/explorer.py
> Store signals in absolute path option

- orion/pipelines/verified/tadgan/tadgan_viz.json
based on the question in #239, we already support visualization output.
this PR is to give an example of a pipeline with viz output
> TadGAN pipeline with visualization option

- tutorials/tulog/Tulog.ipynb
> Fix Tulog tutorial testing

- setup.cfg
- setup.py
- tasks.py
* update setup development requirements
* fix check minimum task
* update flake8 ignore list in `setup.cfg`
> General Housekeeping

- docs/user_guides/primitives_pipelines/pipelines.rst
- docs/user_guides/primitives_pipelines/primitives.rst
- docs/user_guides/primitives_pipelines/primitives/AER.rst
- orion/benchmark.py
- orion/pipelines/verified/aer/aer.json
- orion/pipelines/verified/aer/aer_artificialwithanomaly.json
- orion/pipelines/verified/aer/aer_msl.json
- orion/pipelines/verified/aer/aer_realadexchange.json
- orion/pipelines/verified/aer/aer_realawscloudwatch.json
- orion/pipelines/verified/aer/aer_realtraffic.json
- orion/pipelines/verified/aer/aer_realtweets.json
- orion/pipelines/verified/aer/aer_smap.json
- orion/pipelines/verified/aer/aer_yahooa1.json
- orion/pipelines/verified/aer/aer_yahooa2.json
- orion/pipelines/verified/aer/aer_yahooa3.json
- orion/pipelines/verified/aer/aer_yahooa4.json
- orion/primitives/aer.py
- orion/primitives/jsons/orion.primitives.aer.AER.json
- orion/primitives/jsons/orion.primitives.aer.score_anomalies.json
Resolve #286 
**New**
- Add aer primitive, json files, and pipeline files
> Add AER (autoencoder w/ regression) model to benchmark

- orion/pipelines/verified/tadgan/tadgan_viz.json
> Updated tadgan_viz.json

- docs/user_guides/primitives_pipelines/primitives/DenseSeq2Seq.rst
- docs/user_guides/primitives_pipelines/primitives/LSTMSeq2Seq.rst
- orion/pipelines/verified/dense_autoencoder/dense_autoencoder.json
- orion/pipelines/verified/lstm_autoencoder/lstm_autoencoder.json
- orion/pipelines/verified/lstm_autoencoder/lstm_autoencoder_gpu.json
- orion/primitives/jsons/keras.Sequential.DenseSeq2Seq.json
- orion/primitives/jsons/keras.Sequential.LSTMSeq2Seq.json
- setup.py
- tutorials/Multivariate_Input.ipynb
* update autoencoder primitives to include a new variable `window_size`
* pin `protobuf<4`
> Update AE to work with any `window_size`

- orion/primitives/tadgan.py
- setup.py
> Allow `tadgan` to change `batch_size`

- orion/core.py
- tests/test_core.py
> Add ``__repr__`` function for useful representation of ``Orion`` instance

- .github/workflows/latest-dependencies.yml
- setup.py
* edit checker to run every week at 00:00 UTC Monday
> Change frequency of dependency checker

- docs/user_guides/primitives_pipelines/pipelines.rst
- docs/user_guides/primitives_pipelines/primitives.rst
- docs/user_guides/primitives_pipelines/primitives/VAE.rst
- orion/pipelines/sandbox/vae/vae.json
- orion/pipelines/sandbox/vae/vae_artificialwithanomaly.json
- orion/pipelines/sandbox/vae/vae_msl.json
- orion/pipelines/sandbox/vae/vae_realadexchange.json
- orion/pipelines/sandbox/vae/vae_realawscloudwatch.json
- orion/pipelines/sandbox/vae/vae_realtraffic.json
- orion/pipelines/sandbox/vae/vae_realtweets.json
- orion/pipelines/sandbox/vae/vae_smap.json
- orion/pipelines/sandbox/vae/vae_viz.json
- orion/pipelines/sandbox/vae/vae_yahooa1.json
- orion/pipelines/sandbox/vae/vae_yahooa2.json
- orion/pipelines/sandbox/vae/vae_yahooa3.json
- orion/pipelines/sandbox/vae/vae_yahooa4.json
- orion/primitives/jsons/orion.primitives.vae.VAE.json
- orion/primitives/vae.py
**New Pipeline**
- Add vae primitive, json files, and pipeline files
- Currently, it resides in the sandbox folder.
> vae (Variational Autoencoders) pipeline implementation

- orion/pipelines/verified/aer/aer_viz.json
> AER pipeline with visualization option

- orion/core.py
> Create a variable for `mlpipeline` in `orion.evaluate`

- setup.py
> Update `xlsxwriter` in `setup.py`

- orion/primitives/timeseries_anomalies.py
- tests/primitives/test_timeseries_anomalies.py
Hi, I'm impressed with your code. 
Looking at the code, I found something strange, so I fixed it. 
I wonder if the value of best_cost needs to be changed.
Thank you for reading.
> Revise timeseries_anomalies.py

- .github/workflows/tests.yml
new macos image causes errors.
remove macos py3.7 from tests.
> Update github actions for ``macos`` image

- docker/orion-jupyter.Dockerfile
- docker/package.sh
> Fix Docker builds

- orion/pipelines/sandbox/matrixprofile/matrixprofile.json
- orion/pipelines/sandbox/matrixprofile/matrixprofile_artificialwithanomaly.json
- orion/pipelines/sandbox/matrixprofile/matrixprofile_msl.json
- orion/pipelines/sandbox/matrixprofile/matrixprofile_realadexchange.json
- orion/pipelines/sandbox/matrixprofile/matrixprofile_realawscloudwatch.json
- orion/pipelines/sandbox/matrixprofile/matrixprofile_realtraffic.json
- orion/pipelines/sandbox/matrixprofile/matrixprofile_realtweets.json
- orion/pipelines/sandbox/matrixprofile/matrixprofile_smap.json
- orion/pipelines/sandbox/matrixprofile/matrixprofile_ucr.json
- orion/pipelines/sandbox/matrixprofile/matrixprofile_yahooa1.json
- orion/pipelines/sandbox/matrixprofile/matrixprofile_yahooa2.json
- orion/pipelines/sandbox/matrixprofile/matrixprofile_yahooa3.json
- orion/pipelines/sandbox/matrixprofile/matrixprofile_yahooa4.json
- orion/primitives/jsons/orion.primitives.timeseries_anomalies.find_anomalies.json
- orion/primitives/jsons/stumpy.stump.json
- orion/primitives/timeseries_anomalies.py
- setup.py
- tests/primitives/test_timeseries_anomalies.py
- tutorials/pipelines/matrixprofile.ipynb
> Matrix Profile Pipeline

- orion/primitives/jsons/keras.Sequential.DenseSeq2Seq.json
- orion/primitives/jsons/keras.Sequential.LSTMSeq2Seq.json
- orion/primitives/jsons/orion.primitives.aer.AER.json
- orion/primitives/jsons/orion.primitives.vae.VAE.json
- orion/primitives/vae.py
- setup.py
- tutorials/tulog/model.py
> Add python 3.9

- orion/benchmark.py
- tests/test_benchmark.py
> Resume parameter in benchmark

- orion/benchmark.py
> Make pipelines argument accept dictionary

- orion/benchmark.py
> Allow multiple types for benchmark arguments

- .github/workflows/tests.yml
- orion/pipelines/sandbox/lnn/lnn.json
- orion/pipelines/sandbox/lnn/lnn_artificialwithanomaly.json
- orion/pipelines/sandbox/lnn/lnn_msl.json
- orion/pipelines/sandbox/lnn/lnn_realadexchange.json
- orion/pipelines/sandbox/lnn/lnn_realawscloudwatch.json
- orion/pipelines/sandbox/lnn/lnn_realtraffic.json
- orion/pipelines/sandbox/lnn/lnn_realtweets.json
- orion/pipelines/sandbox/lnn/lnn_smap.json
- orion/pipelines/sandbox/lnn/lnn_ucr.json
- orion/pipelines/sandbox/lnn/lnn_viz.json
- orion/pipelines/sandbox/lnn/lnn_yahooa1.json
- orion/pipelines/sandbox/lnn/lnn_yahooa2.json
- orion/pipelines/sandbox/lnn/lnn_yahooa3.json
- orion/pipelines/sandbox/lnn/lnn_yahooa4.json
- orion/primitives/adapters/ncps.py
- orion/primitives/jsons/keras.Sequential.LTCTimeSeriesRegressor.json
- setup.py
- tests/primitives/adapters/test_ncps.py
> LNN Implementation

- orion/pipelines/sandbox/lnn/lnn_msl.json
- orion/pipelines/sandbox/lnn/lnn_smap.json
- orion/pipelines/sandbox/lnn/lnn_ucr.json
- orion/pipelines/sandbox/lnn/lnn_viz.json
* adjust the hyperparameter settings for LNN
* add `__init__.py` file in adapters sub-model
* fix `lnn_viz` pipeline
> Amend LNN hyperparameters

- .github/workflows/docs.yml
- README.md
- docs/getting_started/install.rst
* update supported python list in docs
> Update docs python

- .github/workflows/latest-dependencies.yml
* update python version in dependency tests
> Update Python for Dependency Test

- orion/pipelines/verified/arima/arima.json
- orion/pipelines/verified/arima/arima_artificialwithanomaly.json
- orion/pipelines/verified/arima/arima_msl.json
- orion/pipelines/verified/arima/arima_realadexchange.json
- orion/pipelines/verified/arima/arima_realawscloudwatch.json
- orion/pipelines/verified/arima/arima_realtraffic.json
- orion/pipelines/verified/arima/arima_realtweets.json
- orion/pipelines/verified/arima/arima_smap.json
- orion/pipelines/verified/arima/arima_ucr.json
- orion/pipelines/verified/arima/arima_yahooa1.json
- orion/pipelines/verified/arima/arima_yahooa2.json
- orion/pipelines/verified/arima/arima_yahooa3.json
- orion/pipelines/verified/arima/arima_yahooa4.json
* update primitive name to use the latest version `statsmodel.tsa.arima.model.ARIMA`
* remove redundant `init_params`
* add an extra `numpy.reshape` primitive after arima primitive to account for `(x,)` case which should be `(x, 1)`
> update ARIMA primitive and pipeline

- tests/test_core.py
> Update `test_core` file

- .github/workflows/tests.yml
* remove ubuntu from minimum tests
* revisit to increase min req
> Update minimum test images

- .github/workflows/tests.yml
- Makefile
- orion/primitives/units.py
- setup.py
- tasks.py
* add an option to install dependencies of `pretrained` models
* update tests to cover `pretrained` pipelines
> Make pretrained models optional to install

- orion/primitives/aer.py
- setup.py
> Unpin ``scikit-learn`` and fix ``MinMaxScaler``

- .github/workflows/tests.yml
- tasks.py
* pause testing pretrained models for 3.10, only support 3.11
> Keep python 3.11 support for pretrained models

- .github/workflows/tests.yml
* remove python3.8 from tutorial tests
* update with only removing from windows
> Update github actions tutorial tests

- .github/workflows/tests.yml
* compatibility issues with new release of `mistune==3.1.0` and ``nbconvert``.
* details in https://github.com/jupyter/nbconvert/issues/2198
> Cap ``mistune``

- orion/pipelines/pretrained/units/units.json
Change units pipeline params to be consistent with other params
> Modify `units` pipeline `find_anomalies` params

- tutorials/Convert_NASA_Data_to_Orion_Format.ipynb
- tutorials/Convert_UCR_Data_to_Orion_Format.ipynb
- tutorials/Evaluating_an_Orion_Pipeline.ipynb
- tutorials/Orion_on_Custom_Data.ipynb
- tutorials/Orion_with_Multivariate_Input.ipynb
> Add Colab link to tutorials

- orion/benchmark.py
> remove pipeline saving from benchmark default
